[project]
name = "alinarum-svc-main"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.12"
dependencies = [
    "fastapi>=0.116.1",
    "pydantic>=2.11.9",
    "pydantic-settings>=2.10.1",
    "pymongo>=4.15.0",
    "scalar-fastapi>=1.4.0",
    "tomli>=2.2.1",
    "uvicorn>=0.35.0",
]
